name: YouOweMe
description: Making it simpler to track those chillars.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  rxdart: ^0.23.1
  device_preview: ^0.4.2
  graphql_flutter: ^3.0.0
  provider: ^4.0.4
  cloud_firestore: ^0.13.4+2

  # Used by Artemis (Code Gen)
  json_serializable: ^3.3.0
  equatable: ^1.1.1
  meta: ^1.1.8
  sliding_up_panel: ^1.0.1
  contacts_service: ^0.3.10
  permission_handler: ^5.0.0+hotfix.3

dev_dependencies:
  artemis:
    git:
      url: git://github.com/comigor/artemis.git
      ref: beta
  build_runner: ^1.8.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Aileron
      fonts:
        - asset: assets/fonts/Aileron/Aileron-Regular.otf
        - asset: assets/fonts/Aileron/Aileron-UltraLight.otf
          weight: 100
        - asset: assets/fonts/Aileron/Aileron-Thin.otf
          weight: 200
        - asset: assets/fonts/Aileron/Aileron-Light.otf
          weight: 300
        - asset: assets/fonts/Aileron/Aileron-Regular.otf
          weight: 400
        - asset: assets/fonts/Aileron/Aileron-Regular.otf
          weight: 500
        - asset: assets/fonts/Aileron/Aileron-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Aileron/Aileron-Bold.otf
          weight: 700
        - asset: assets/fonts/Aileron/Aileron-Heavy.otf
          weight: 800
        - asset: assets/fonts/Aileron/Aileron-Black.otf
          weight: 900
        - asset: assets/fonts/Aileron/Aileron-UltraLightItalic.otf
        - asset: assets/fonts/Aileron/Aileron-ThinItalic.otf
        - asset: assets/fonts/Aileron/Aileron-SemiBoldItalic.otf
        - asset: assets/fonts/Aileron/Aileron-LightItalic.otf
        - asset: assets/fonts/Aileron/Aileron-HeavyItalic.otf
        - asset: assets/fonts/Aileron/Aileron-BoldItalic.otf
        - asset: assets/fonts/Aileron/Aileron-BlackItalic.otf
