on:
  schedule:
    - cron: * 6 * * 3
jobs:
  test:
    name: Flutter Dependency Bot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "beta"
      - name: Run Package
        uses: tianhaoz95/update-flutter-packages@v0.0.1
        with:
          flutter-project: "./mobileApp"
          git-email: "preetjdp123@gmail.com"
          git-name: "Preet Parekh"
          token: ${{ secrets.GITHUB_TOKEN }}
